apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dvecdb

commonLabels:
  app.kubernetes.io/name: dvecdb
  app.kubernetes.io/part-of: dvecdb-platform

resources:
- deployment.yaml
- service.yaml
- configmap.yaml
- pdb.yaml
- hpa.yaml

configMapGenerator:
- name: dvecdb-config
  behavior: merge
  literals:
  - LOG_LEVEL=info
  - RUST_LOG=info

images:
- name: dvecdb/server
  newTag: "0.1.7"
