apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: dvecdb
  labels:
    app: dvecdb
    prometheus: kube-prometheus
spec:
  selector:
    matchLabels:
      app: dvecdb
  endpoints:
  - port: metrics
    interval: 30s
    path: /metrics
    scheme: http
